function generatePuebloName() {
  const prefix = [
    "",
    "",
    "",
    "Villa",
    "Mira",
    "El ",
    "La ",
    "Torre",
    "Sierra",
    "Real ",
    "San ",
    "Santa ",
    "Cumbre ",
    "Monte ",
    "Bella",
    "Nuevo ",
    "Viejo ",
    "Gran ",
    "Brisa",
    "Calores ",
    "Nueva ",
    "Pueblo ",
    "Poblao ",
    "Isla ",
    "Cerro ",
    "Valle ",
    "Sube ",
    "Baja ",
    "Bosquecillo ",
    "Colina ",
    "Miel",
    "Aguas ",
  ];
  const nouns = [
    "",
    "",
    "",
    "Turbio",
    "Conejos",
    "Floripondios ",
    "Brisilla",
    "Camellos",
    "Valles",
    "Torrijas",
    "Pan",
    "Pepino",
    "Pijo",
    "Pollos",
    "Cebolla",
    "Cellajo",
    "Churro",
    "Almóndiga",
    "Chirimoya",
    "Patatas",
    "Churro",
    "Cacahuete",
    "chamusquina",
    "Pachanga",
    "Zampabollos",
    "Gorgorito",
    "Tiquismiquis",
    "Chuches",
    "Cocretas",
    "Pechuga",
    "Cayetano",
    "Madalenas",
    "Murciegalo",
    "Aguacate",
    "Zapato",
    "Zoquete",
    "Pimpollo",
    "Pezones", 
  ];
  const suffix = [
    "",
    "",
    "",
    " de la reina",
    " de arriba",
    " de abajo",
    " de al lado",
    " del monte",
    " Montañoso",
    " del rey",
    " del valle",
    " de la Fuente",
    " de la charca",
    " de los calores",
    " de los gatos",
    " del Sur",
    " del Norte",
    " del Este",
    " del Oeste",
    " de las cumbres",
    " de los pinos",
    " de la tobaya",
    " del cateto",
    " del abujero",
    " de la Cuestecilla",
    " de la Torre",
    " del pie",
    " de la pierna",
    " de la barriga",
    " de la roca",
    " de la nalga",
    " Salsero",
    " Tropical",
    " del Sofoco",
    " Abrasador",
  ];
  const randomPrefix = prefix[Math.floor(Math.random() * prefix.length)];
  const randomNoun = nouns[Math.floor(Math.random() * nouns.length)];
  const randomSuffix = suffix[Math.floor(Math.random() * suffix.length)];
  return `${randomPrefix}${randomNoun}${randomSuffix}`;
}

window.addEventListener("DOMContentLoaded", (event) => {
  const button = document.getElementById("generate");
  button.addEventListener("click", () => {
    const response = document.getElementById("response");
    const responseText = generatePuebloName();
    response.innerText = responseText;
  });
});
